project:
  type: website
  output-dir: docs

website:
  title: "Haytam Khalfi - MBA Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Resume"
        href: resume.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Skills"
        href: skills.qmd
      - text: "Leadership"
        href: leadership.qmd
      - text: "Contact"
        href: contact.qmd

format:
  html:
    theme: cosmo
    toc: true
    smooth-scroll: true
